books/urls.py
from django.urls import path, include

from books import views

urlpatterns = [
	path('', views.index, name='index'),
	path('add_book/', views.add_book, name='add_book'),
	path('edit_book/<int:book_id>/', views.edit_book, name='edit_book'),
	path('delete/<int:id>/', views.delete, name='delete'),
	path('search/', views.search, name='search'),
	path('make_request/<int:id>/', views.make_request, name='make_request'),
]

bookself/urls.py
from django.contrib import admin
from django.urls import path, include

from bookself import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('admin/', admin.site.urls),
]

users/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from users import views

# import notifications

urlpatterns = [
	path('home/', views.home, name='home'),
	path('register/', views.register, name='register'),
	path('login/', views.login, name='login'),
	path('logout/', views.logout, name='logout'),		

	# books module
	path('books/', include(('books.urls', 'books'), namespace='books')),
	# bookrequests module
	path('requests/', include(('bookrequests.urls', 'requests'), namespace='requests')),
	# notifications
    # url('^inbox/notifications/', include(notifications.urls)),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserInfo(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	address = models.CharField(max_length = 200)
	dob = models.DateField()

users/views.py
from django.shortcuts import render

from django.urls import reverse

from django.contrib import messages

from django.contrib.auth import authenticate
from django.contrib.auth import login as djlogin
from django.contrib.auth import logout as djlogout

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from users.models import UserInfo

from django.http import HttpResponse, HttpResponseRedirect

from bookself.misc import anonymous_required

@login_required
def logout(request):
    djlogout(request)
    return render(request, 'logout.html')

@anonymous_required
def login(request):
    # check if the form was submitted
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        # next page to redirect to
        next_url = request.POST.get('next')

        # default redirect
        if not next_url:
            next_url = reverse('users:home')

        user = authenticate(username=username, password=password)

        if user is not None:
            djlogin(request, user)

            return HttpResponseRedirect(next_url)
        else:
            messages.error(request,
             'The username or password you entered is incorrect')

            return render(request, 'login.html')
    else:
        # go to the login page
        return render(request, 'login.html')

@login_required
def home(request):
    return render(request, 'home.html')

@anonymous_required
def register(request):
    

    if request.method == 'POST':
        message = ''

        username = request.POST.get('username')
        email    = request.POST.get('email')  
        fname    = request.POST.get('firstName')  
        lname    = request.POST.get('lastName')  
        address  = request.POST.get('address')  
        dob      = request.POST.get('dob')  
        password = request.POST.get('password')  

        inputs = (username, email, 
                fname, lname, address,
                address, dob, password)   

        if User.objects.filter(username__exact=username).exists():
            message = 'name_taken'

        elif User.objects.filter(email__exact=email).exists():
            message = 'email_taken'
        
        if not message:
            # create a new user 
            try:
                new_user = User.objects.create_user(
                                username=username, email=email, password=password,
                                first_name=fname,
                                last_name=lname
                            )

                new_user_info = UserInfo(user = new_user, address = address, dob = dob)
                new_user_info.save()
                djlogin(request, new_user)

            except e:
                print(str(e))
            
            message = "no_error"

        return HttpResponse(message) 
    else:
        return render(request, 'register.html')

users/templates/_left_nav.html
<ul class="nav nav-tabs nav-stacked">
	<li>
		<a href="{% url 'users:home' %}">Home</a>
	</li>

	<li>
		<a href="{% url 'users:books:index' %}">My Books</a>
	</li>

	<li>
		<a href="{% url 'users:requests:borrowed' %}">Requested Books</a>
	</li>

	<li>
		<a href="{% url 'users:requests:lent' %}">Lent Books</a>
	</li>

	<li>
		<a href="#">Account</a>
	</li>
</ul>

users/templates/users_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Bookself</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'starter-template.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">Bookself</a>
        </div>

          <form class="navbar-form navbar-left" 
           method="post" action="{% url 'users:books:search' %}" id="search">
             {% csrf_token %}
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search" 
                name="query">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
          </form>  
          
          
        

        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'users:logout' %}">Logout</a></li>
          </ul>
        </div><!--/.nav-collapse -->

      </div>
    </nav>

    <div class="container">
      <div class="starter-template">
              
      <div class="col-md-3" id="left-nav">
        {% include "_left_nav.html" %}
      </div>  

      <div class="col-md-9">
        {% if messages %}
          {% for msg in messages %}
            <div class="alert alert-{{msg.tags}}">{{ msg }}</div>  
          {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock %}
      </div>
        
      </div>
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>