books/urls.py
from django.urls import path, include

from books import views

urlpatterns = [
	path('', views.index, name='index'),
	path('add_book/', views.add_book, name='add_book'),
	path('edit_book/<int:book_id>/', views.edit_book, name='edit_book'),
	path('delete/<int:id>/', views.delete, name='delete'),
	path('search/', views.search, name='search'),
	path('make_request/<int:id>/', views.make_request, name='make_request'),
]

bookself/urls.py
from django.contrib import admin
from django.urls import path, include

from bookself import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('admin/', admin.site.urls),
]

users/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from users import views

# import notifications

urlpatterns = [
	path('home/', views.home, name='home'),
	path('register/', views.register, name='register'),
	path('login/', views.login, name='login'),
	path('logout/', views.logout, name='logout'),		

	# books module
	path('books/', include(('books.urls', 'books'), namespace='books')),
	# bookrequests module
	path('requests/', include(('bookrequests.urls', 'requests'), namespace='requests')),
	# notifications
    # url('^inbox/notifications/', include(notifications.urls)),
]

templates/about.html
{% extends "base.html" %}

{% block content %}

This is the about page. Needs to be updated.

{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Bookself</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'starter-template.css' %}" rel="stylesheet">
    {# <link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}"> #}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">Bookself</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'contact' %}">Contact</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'users:register' %}">Signup</a></li>
            <li><a href="{% url 'users:login' %}">Login</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <div class="starter-template">
        {% if messages %}
          {% for msg in messages %}
            <div class="alert alert-{{msg.tags}}">{{ msg }}</div>  
          {% endfor %}
        {% endif %}
        
        {% block content %}
        {% endblock %}
      </div>
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/contact.html
{% extends "base.html" %}

{% block content %}

Chandan - cy@test.com <br>
Ananth - ant@test.com

{% endblock content %}

templates/index.html
{% extends "base.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static "css/index.css" %}">

<img src="{% static "img/Bookzilla.png" %}" id="main-logo">
{% endblock content %}